import doubly_linked_list as dll
obj=dll.Doubly_LinkedList()
obj.Insert(2)
obj.Insert(3)
obj.Insert(4)
obj.Insert(5)
obj.Insert(6)
obj.Insert(7)
obj.Insert(8)
obj.Access()
obj.Delete(4)
obj.Insert(9)
obj.Delete(43)
obj.Access()
obj.BackTrack()
obj.Search(5)
obj.Search(55)